### ISSUE TITLE
source not found (com.hdoapp:ffmpeg-kit-https:6.0-2.LTS)

### ISSUE THREAD

**Issue by sandeepunify** [nightmarefsm/ffmpeg-kit-new#2]
I am trying for flutter app
and I am getting error source not found (com.hdoapp:ffmpeg-kit-https:6.0-2.LTS)

Please help about this error

**Comment by nightmarefsm** [comment]
```
mvn install:install-file \
  -Dfile=ffmpeg-kit-https-6.0-2.LTS.aar \
  -DgroupId=com.arthenica \
  -DartifactId=ffmpeg-kit-https \
  -Dversion=6.0-2.LTS \
  -Dpackaging=aar
```
After install use like this

```
 ffmpeg_kit_flutter:
    git:
      url: https://github.com/nightmarefsm/ffmpeg-kit-new
      ref: flutter_3.29_standard
      path: flutter/flutter
```

Try now! Hopefully, it will work—I’ve fixed it!
